export const gratitudePhrases = [
    "Psst! A tiny chocolate bar makes a big thank you!",
    "How about a little sweet treat for your neighbor's kindness?",
    "Goodies for good deeds! Maybe a small snack for them?",
    "A handwritten note or a small cookie? Just a thought!",
    "Small gifts make big friends. A little chocolate maybe?",
    "Spread the love! A little candy goes a long way.",
    "Kindness is sweet, and so are brownies! Suggestion?",
    "A high-five is great, but a chocolate is better!",
    "Why not drop a tiny 'thinking of you' treat?",
    "Borrowing is easier when followed by a cookie!",
    "A small bag of coffee or tea? A wonderful way to say thanks.",
    "Warm their heart with a warm note and a cold chocolate!",
    "Neighborly love in a wrapper! Maybe a small goodie?",
    "The best way to say thanks? Something yummy!",
    "Sweeten the community! How about a little treat?",
    "A tiny gesture, a huge smile. Maybe a small candy?",
    "Chocolates are the international language of 'You're awesome!'",
    "A little cookie, a lot of thanks!",
    "Keep the circle of giving going with a small snack!",
    "A handwritten 'You Rock' note + a chocolate? Perfect.",
    "Surprise them with a little something sweet!",
    "A small treat for a big favor—it's the Boho way!",
    "Good vibes and good cookies! Just a suggestion.",
    "A little spice or a little sweet? A tiny gift maybe?",
    "Thoughtfulness in a bite! How about a small treat?",
    "A little chocolate, a big heart!",
    "Saying thanks with a snack is the best kind of thanks!",
    "A small token of gratitude—maybe a sweet one?",
    "Keep the borrow-vibes high with a tiny treat!",
    "A little candy, a lot of community!",
    "Make their day with a tiny sweet surprise!",
    "Kindness is contagious—pass it on with a cookie!",
    "A small gesture for a big help—chocolate time?",
    "The sweetest thank you is the one you can eat!",
    "Neighborly love—served with a side of brownies?",
    "A little goodie for a good soul!",
    "Spread the joy with a tiny chocolate bar!",
    "A small snack for a big impact!",
    "Kindness deserves a cookie (or two)!",
    "Say it with sweetness! A small treat maybe?",
    "A tiny gift for a huge help—neighborly love!",
    "Keep it sweet! A little chocolate for your friend?",
    "A small bite of gratitude—how about a treat?",
    "Goodies are the secret sauce of a great neighborhood!",
    "A little sugar, a lot of thanks!",
    "Make it memorable with a tiny sweet gesture!",
    "A small token for a massive favor—chocolate?",
    "Sweet vibes only! Maybe a small snack?",
    "A little cookie goes a long way in community!",
    "Handmade or store-bought, a little treat is always right!",
    "Chocolates: because neighbors who help are the best!",
    "A small bag of treats for a big-hearted neighbor!",
    "Spread the warmth with a little hot cocoa mix?",
    "A tiny sweet, a giant thank you!",
    "Flavor their day with a little gratitude snack!",
    "A little chocolate for the soul who helped yours!",
    "Community spirit in a candy bar! Just a thought.",
    "A small box of goodies—the perfect follow-up!",
    "Sweeten their afternoon with a tiny surprise!",
    "A little crunch, a little sweet, a lot of thanks!",
    "The best neighbors get the best chocolates!",
    "A small token of your appreciation—maybe edible?",
    "Keep the kindness flowing with a tiny goodie!",
    "A little treat for the person who had your back!",
    "Sweetness in every bite—a great way to say thanks!",
    "A small snack for a super neighbor!",
    "Gratitude tastes better when it's chocolate!",
    "A tiny gift for a legendary favor!",
    "Show some love with a little sweet something!",
    "A small cookie for a big smile!",
    "Keep the community cool with a tiny treat!",
    "A little sugar for the sweetest neighbor!",
    "A small goodie for a great helping hand!",
    "Sweeten the deal with a tiny thank you snack!",
    "A little bite of kindness—how about a chocolate?",
    "Neighborly gratitude in a small wrapper!",
    "A tiny gift, a massive 'You're the best!'",
    "Spread the sweet vibes with a small goodie!",
    "A little treat for the heart that helped!",
    "Cookies: the universal currency of thank you!",
    "A small chocolate for a big-time help!",
    "Keep it neighborly, keep it sweet!",
    "A tiny snack for a total hero!",
    "Sweeten their life just a little bit today!",
    "A small bag of treats—the ultimate gratitude!",
    "A little flavor for your favorite helper!",
    "Chocolates are like a hug you can eat!",
    "A small bite of thanks—just a suggestion!",
    "Neighborly love is better with a cookie!",
    "A tiny sweet surprise for a super soul!",
    "A little goodie for the person of the hour!",
    "Spread the kindness with a small chocolate!",
    "A small token of thanks—sweet or salty?",
    "Kindness is a gift—pay it back with a snack!",
    "A little treat for the neighbor who cares!",
    "Sweeten the neighborhood one treat at a time!",
    "A tiny snack for a top-tier neighbor!",
    "Gratitude served sweet! How about a chocolate?",
    "A small gesture, a big heart, and a little candy!",
    "The best thanks comes with a little something yummy!"
];

export const getRandomPhrase = () => {
    return gratitudePhrases[Math.floor(Math.random() * gratitudePhrases.length)];
};
