export const sharingQuotes = [
    "Sharing is caring, but borrowing is community!",
    "A drill shared is a hole halved.",
    "Your neighbor's lawnmower is your lawnmower (if you ask nicely).",
    "Happiness is only real when shared.",
    "What's mine is yours, as long as you bring it back!",
    "Community: where my stuff becomes our stuff.",
    "Live simply, share generously.",
    "The best things in life aren't things, they're shared.",
    "Sharing a tool is like sharing a part of your story.",
    "Borrowing: the ultimate social network.",
    "Why buy when you can borrow a friend's?",
    "Small acts of sharing lead to big community vibes.",
    "A toolkit shared is a neighborhood empowered.",
    "Kindness starts with a shared ladder.",
    "Sharing bread is good, sharing a pressure washer is better!",
    "The more you share, the more you have.",
    "Generosity is the best neighbor.",
    "Borrowing with love, returning with thanks.",
    "Your clutter might be your neighbor's solution!",
    "Sharing: because one air fryer is enough for the whole street.",
    "Community is built one borrowed hammer at a time.",
    "Shared items, shared hearts.",
    "A neighbor in need is a neighbor to share with.",
    "Sharing is the highest form of community trust.",
    "Let's make 'mine' and 'thine' into 'ours'.",
    "The joy of sharing is a gift to yourself.",
    "Borrowing gear, building friendships.",
    "A shared bike is a journey together.",
    "Sharing is the glue that holds a village together.",
    "Give what you can, borrow what you need.",
    "A community that shares together, stays together.",
    "Tools are meant to be used, not just owned.",
    "Share the load, share the love.",
    "Borrowing: cheaper than therapy, better for the soul.",
    "A borrowed book is a shared world.",
    "Kindness is a boomerang—share it around!",
    "Sharing is the new owning.",
    "Your garage called: it wants to share some tools!",
    "The best neighbors share their secrets and their spoons.",
    "Sharing creates a web of kindness.",
    "A neighbor's helping hand is the best tool in the shed.",
    "Borrowing: because sharing is the ultimate flex.",
    "Common ground starts in the common shed.",
    "Sharing is a conversation without words.",
    "The circle of sharing never stops.",
    "A shared kitchen scale makes for a sweeter neighborhood.",
    "Borrowing is a vote for community.",
    "Don't just own it, share the magic!",
    "Sharing is the art of giving without losing.",
    "A shared garden thrives on shared tools.",
    "The best stories start with 'Can I borrow that?'",
    "Sharing is the language of the heart.",
    "A neighborly share is a victory for everyone.",
    "Borrowing: the original circular economy.",
    "Sharing turns strangers into neighbors.",
    "Your extra chair is someone's welcome seat.",
    "Sharing is the ultimate life hack.",
    "A shared tent is a shared adventure.",
    "Borrowing: because your storage unit is full enough.",
    "Sharing is the spark that lights up a street.",
    "A shared mixer makes the best neighborhood treats.",
    "Kindness is the currency of a sharing community.",
    "Sharing: it's not just for toddlers!",
    "A borrowed camera captures shared memories.",
    "Sharing is the pathway to a peaceful planet.",
    "A shared vacuum is a clean conscience.",
    "Borrowing: making the world smaller and hearts bigger.",
    "Sharing is the secret to a happy home.",
    "A shared telescope sees a bigger universe.",
    "The more we share, the less we need.",
    "Sharing is the ultimate act of optimism.",
    "Your neighbor's success is your success (if you shared the tools).",
    "Sharing is the rhythm of a healthy neighborhood.",
    "A shared board game is a shared laugh.",
    "Borrowing: the smart way to live well.",
    "Sharing is the bridge between us.",
    "A shared slow cooker makes the best community chili.",
    "Sharing is the legacy we leave behind.",
    "Your kindness is your neighbor's strength.",
    "Sharing is the heartbeat of humanity.",
    "A shared umbrella keeps two people dry.",
    "Borrowing: because community is the best asset.",
    "Sharing is the sunshine of the soul.",
    "A shared toolkit is a symphony of service.",
    "Sharing is the ultimate win-win.",
    "Your neighbor's gratitude is the best reward for sharing.",
    "Sharing is the key to unlocking abundance.",
    "A shared world is a better world.",
    "Borrowing: because we're all in this together.",
    "Sharing is the greatest adventure of all.",
    "A shared heart knows no limits.",
    "Sharing is the essence of true wealth.",
    "Your neighbor's smile is the best return on investment.",
    "Sharing is the foundation of a bright future.",
    "A shared journey is a journey of the soul.",
    "Sharing is the ultimate expression of love.",
    "Borrowing: making memories, one item at a time.",
    "Sharing is the most beautiful thing we can do.",
    "A shared life is a life well lived."
];

export const getRandomQuote = () => {
    return sharingQuotes[Math.floor(Math.random() * sharingQuotes.length)];
};
